const styles = {
    floatingButton: {
      position: 'fixed',
      bottom: '20px',
      right: '20px',
      width: '60px',
      height: '60px',
      borderRadius: '50%',
      backgroundColor: '#FF6B35',
      color: 'white',
      border: 'none',
      cursor: 'pointer',
      fontSize: '24px',
      boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
      display: open ? 'none' : 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      transition: 'all 0.3s ease',
      zIndex: 1000,
    },
    overlay: {
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0,0,0,0.5)',
      display: open ? 'block' : 'none',
      zIndex: 1100,
    },
    dialog: {
      position: 'fixed',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
      width: '90%',
      maxWidth: '500px',
      height: '600px',
      maxHeight: '90vh',
      backgroundColor: 'white',
      borderRadius: '12px',
      boxShadow: '0 10px 40px rgba(0,0,0,0.2)',
      display: open ? 'flex' : 'none',
      flexDirection: 'column',
      zIndex: 1200,
      overflow: 'hidden',
    },
    header: {
      backgroundColor: '#FF6B35',
      color: 'white',
      padding: '16px 20px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderRadius: '12px 12px 0 0',
    },
    headerContent: {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
    },
    avatar: {
      width: '40px',
      height: '40px',
      borderRadius: '50%',
      backgroundColor: 'white',
      color: '#FF6B35',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: '20px',
      fontWeight: 'bold',
    },
    headerText: {
      display: 'flex',
      flexDirection: 'column',
    },
    title: {
      fontSize: '18px',
      fontWeight: '600',
      margin: 0,
    },
    status: {
      fontSize: '12px',
      opacity: 0.9,
      margin: 0,
    },
    closeButton: {
      backgroundColor: 'transparent',
      border: 'none',
      color: 'white',
      fontSize: '24px',
      cursor: 'pointer',
      padding: '4px 8px',
      lineHeight: 1,
    },
    messagesContainer: {
      flex: 1,
      padding: '20px',
      backgroundColor: '#f5f5f5',
      overflowY: 'auto',
      display: 'flex',
      flexDirection: 'column',
      gap: '16px',
    },
    messageRow: {
      display: 'flex',
      gap: '8px',
    },
    messageRowUser: {
      display: 'flex',
      gap: '8px',
      justifyContent: 'flex-end',
    },
    messageAvatar: {
      width: '32px',
      height: '32px',
      borderRadius: '50%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: '16px',
      fontWeight: 'bold',
      flexShrink: 0,
    },
    botAvatar: {
      backgroundColor: '#FF6B35',
      color: 'white',
    },
    userAvatar: {
      backgroundColor: '#1976d2',
      color: 'white',
    },
    messageBubble: {
      padding: '12px 16px',
      borderRadius: '12px',
      maxWidth: '70%',
      wordWrap: 'break-word',
    },
    botBubble: {
      backgroundColor: 'white',
      color: '#333',
      borderBottomLeftRadius: '4px',
      boxShadow: '0 1px 2px rgba(0,0,0,0.1)',
    },
    userBubble: {
      backgroundColor: '#FF6B35',
      color: 'white',
      borderBottomRightRadius: '4px',
    },
    messageText: {
      margin: 0,
      fontSize: '14px',
      lineHeight: '1.5',
      whiteSpace: 'pre-line',
    },
    timestamp: {
      fontSize: '11px',
      opacity: 0.7,
      marginTop: '4px',
      display: 'block',
    },
    typingIndicator: {
      display: 'flex',
      gap: '8px',
      alignItems: 'center',
    },
    typingDots: {
      display: 'flex',
      gap: '4px',
      padding: '12px 16px',
      backgroundColor: 'white',
      borderRadius: '12px',
      borderBottomLeftRadius: '4px',
    },
    dot: {
      width: '8px',
      height: '8px',
      borderRadius: '50%',
      backgroundColor: '#FF6B35',
      animation: 'bounce 1.4s infinite ease-in-out',
    },
    quickRepliesContainer: {
      padding: '12px 20px',
      backgroundColor: '#f5f5f5',
      display: 'flex',
      gap: '8px',
      flexWrap: 'wrap',
    },
    quickReplyButton: {
      padding: '8px 16px',
      backgroundColor: 'white',
      border: '1px solid #ddd',
      borderRadius: '20px',
      cursor: 'pointer',
      fontSize: '13px',
      transition: 'all 0.2s',
    },
    inputContainer: {
      padding: '16px 20px',
      backgroundColor: 'white',
      display: 'flex',
      gap: '12px',
      borderRadius: '0 0 12px 12px',
    },
    input: {
      flex: 1,
      padding: '12px 16px',
      border: '1px solid #ddd',
      borderRadius: '24px',
      fontSize: '14px',
      outline: 'none',
    },
    sendButton: {
      width: '48px',
      height: '48px',
      borderRadius: '50%',
      backgroundColor: '#FF6B35',
      color: 'white',
      border: 'none',
      cursor: 'pointer',
      fontSize: '20px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      transition: 'all 0.2s',
    },
    sendButtonDisabled: {
      backgroundColor: '#ccc',
      cursor: 'not-allowed',
    },
  };


export default styles;